version: "3.7"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./MySQL_Volume:/var/lib/mysql:rw